# Program-1 WAP Addition of two number in python Program

In [2]:
a=int(input("enter 1st number "))
b=int(input("enter 2nd number "))
print(a+b)

enter 1st number 141
enter 2nd number 13
154


# Program-2 WAP Armstrong number in python


In [11]:
n=int(input("enter a number"))
s=n
b=len(str(n))
sum1=0
while n!=0:
    r=n%10
    sum1=sum1+(r**b)
    n=n//10
if s==sum1:
    print("the given number",s,"is armstrong number")
else:
    print("the given number",s,"is not armstrong number")

enter a number153
the given number 153 is armstrong number


# Program-3 WAP Find the square root of a number in python


In [7]:
import math
x=int(input("enter a number"))
math.sqrt(x)

enter a number23


4.795831523312719

# Program-4 WAP to convert binary number into decimal number and vice versa in python


In [14]:
s=float(input("enter a number"))
print("float num in intger",(int(s)))

enter a number3.5
float num in intger 3


In [2]:
s=int(input("enter a number"))
print("intger num in float",(float(s)))

enter a number4
intger num in float 4.0


# Program-5 WAP to sort the elements of the array in ascending order using Bubble/selection/insertion sort technique in python 

In [6]:
arr = [64, 34, 25, 12, 22, 11, 90]
n = len(arr)
for i in range(n-1):
    for j in range(0, n-i-1):
        if arr[j] > arr[j+1]:
            arr[j], arr[j+1] = arr[j+1], arr[j]

print("Sorted array using Bubble Sort:", arr)


Sorted array using Bubble Sort: [11, 12, 22, 25, 34, 64, 90]


In [5]:
arr = [64, 34, 25, 12, 22, 11, 90]
n = len(arr)
for i in range(n):
    min_idx = i
    for j in range(i+1, n):
        if arr[min_idx] > arr[j]:
            min_idx = j
    arr[i], arr[min_idx] = arr[min_idx], arr[i]

print("Sorted array using Selection Sort:", arr)


Sorted array using Selection Sort: [11, 12, 22, 25, 34, 64, 90]


In [4]:
arr = [64, 34, 25, 12, 22, 11, 90]
for i in range(1, len(arr)):
    key = arr[i]
    j = i - 1
    while j >= 0 and key < arr[j]:
        arr[j + 1] = arr[j]
        j -= 1
    arr[j + 1] = key

print("Sorted array using Insertion Sort:", arr)


Sorted array using Insertion Sort: [11, 12, 22, 25, 34, 64, 90]


In [48]:
import numpy as np 
x = np.array([[2,3,4],[2,6,3],[23,5,4]])
print(x)
n=len(x)
n = len(x)
for i in range(n):
    swapped = False
    for j in range(0, n-i-1):
        if x[j] > x[j+1]:
            x[j], x[j+1] = x[j+1], x[j]
            swapped = True
            if not swapped:
                break
print("te aaray",x)                

[[ 2  3  4]
 [ 2  6  3]
 [23  5  4]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# Program-7 WAP palindrome number in python


In [8]:
x=input("enter the number")
if x==x[::-1]:
    print("it is pallindrome number")
else:
    print("it is not pallindrome")




enter the number12321
it is pallindrome number


# WAP to find the status of employee-insured or not under given condition in python. 

# Program-8 MARRIED INSURED MALE & AGE>30 INSURED FEMALE & AGE>25 INSURED


In [16]:
ma=input("enter a married status MARRIED or UNMARRIED  ")
s=input("enter sex M or F  ")
a=int(input("enter your age  "))

if ma=='MARRIED':
    if s=='M':
        if a>30:
            print("all condition Are ensured")
        else:
            print("not satisfied")
elif ma=='MARRIED':
    if s=='F':
        if a>25:
            print("all condition Are ensured")
    else:
        print("not satisfied")  
else:
    print("not satisfied")
    
    
    

enter a married status MARRIED or UNMARRIED  MARRIED
enter sex M or F  M
enter your age  34
all condition Are ensured


# Program-9 WAP large number between three numbers in python


In [4]:
a=int(input("enter 1st number "))
b=int(input("enter 2nd number "))
c=int(input("enter 2nd number ")) 
li=[a,b,c]
print(max(li))

enter 1st number 4
enter 2nd number 425
enter 2nd number 25
425


# Program-10 WAP program to calculate compound interest in python

In [2]:
p=int(input("enter principal amount "))
r=int(input("enter rate of interest "))
t=int(input("enter time "))
si=p*r*t/100
print(si)

enter principal amount 232000
enter rate of interest 2
enter time 133
617120.0


# Program-11 WAP Program for value of 1+1/2+1/3+.....1/n WAP gross salary under given condition. 


In [2]:
n=int(input("enter you number"))
sum = 0.0
for i in range(1, n+1):
    sum = sum +1/i
print(sum)

enter you number5
2.283333333333333


# Program-12 Basic salary>=15000 DA=90% HRA-30%  Basic salary 15000 DA-98% HRA-20%


In [14]:
basic_salary = 20000  
if basic_salary >= 15000:
        DA = basic_salary * 0.90
        HRA = basic_salary * 0.30
        gross_salary = basic_salary + DA + HRA
        print(gross_salary)
else:
    print("Basic salary should be greater than or equal to 15000")
print(gross_salary,"  is  the gross salary for a basic salary of ",basic_salary)

44000.0
44000.0   is  the gross salary for a basic salary of  20000


# Program-13 WAP to demonstrate use of list & related functions in python


In [15]:
l1=[2,3,4,6,634,213,2,4,4,5,9]
l1.append(23)
l1

[2, 3, 4, 6, 634, 213, 2, 4, 4, 5, 9, 23]

In [16]:
l1.copy()

[2, 3, 4, 6, 634, 213, 2, 4, 4, 5, 9, 23]

In [18]:
l1.clear()
l1

[]

In [18]:
l1=[2,3,4,6,634,213,2,4,4,5,9]
l1.sort()
l1

[2, 2, 3, 4, 4, 4, 5, 6, 9, 213, 634]

In [19]:
l1.reverse()
l1

[634, 213, 9, 6, 5, 4, 4, 4, 3, 2, 2]

In [20]:
l1.count(4)


3

In [36]:
l1=[2,3,4,6,634,213,2,4,4,5,9]
l1.extend([23,344])
l1

[2, 3, 4, 6, 634, 213, 2, 4, 4, 5, 9, 23, 344]

In [38]:
l1.insert(2,34)
l1

[2, 3, 34, 34, 4, 6, 634, 213, 2, 4, 4, 5, 9, 23, 344]

In [40]:
l1.pop(2)

34

In [43]:
l1.remove(4)
l1

[2, 3, 6, 634, 213, 2, 4, 4, 5, 9, 23, 344]

# Program-14 WAP to demonstrate use of Dictionary& related functions in python 

In [49]:
dict1={"Name":"Prateek","Roll No":50,"course":"Btech(Aiml)"}
dict1.clear()
dict1

{}

In [50]:
dict1={"Name":"Prateek","Roll No":50,"course":"Btech(Aiml)"}
dict1.copy()


{'Name': 'Prateek', 'Roll No': 50, 'course': 'Btech(Aiml)'}

In [47]:

dict1.fromkeys({'Name',"prateek"})

{'prateek': None, 'Name': None}

In [48]:

dict1.get('Name')


'Prateek'

In [49]:

dict1.items()


dict_items([('Name', 'Prateek'), ('Roll No', 50), ('course', 'Btech(Aiml)')])

In [54]:
dict1={"Name":"Prateek","Roll No":50,"course":"Btech(Aiml)"}
dict1.keys()


dict_keys(['Name', 'Roll No', 'course'])

In [55]:
dict1={"Name":"Prateek","Roll No":50,"course":"Btech(Aiml)"}
print(dict1.pop("Name"))
dict1


Prateek


{'Roll No': 50, 'course': 'Btech(Aiml)'}

In [56]:
dict1={"Name":"Prateek","Roll No":50,"course":"Btech(Aiml)"}
print(dict1.popitem())
dict1


('course', 'Btech(Aiml)')


{'Name': 'Prateek', 'Roll No': 50}

In [51]:
dict1={"Name":"Prateek","Roll No":50,"course":"Btech(Aiml)"}
dict1.setdefault("skills","python")
dict1


{'Name': 'Prateek', 'Roll No': 50, 'course': 'Btech(Aiml)', 'skills': 'python'}

In [52]:

dict1.values()


dict_values(['Prateek', 50, 'Btech(Aiml)', 'python'])

In [54]:

dict1.update({"skills":"R "})
dict1

{'Name': 'Prateek', 'Roll No': 50, 'course': 'Btech(Aiml)', 'skills': 'R '}

# Program-15 WAP to demonstrate use of tuple, set& related functions in python


In [55]:
tu=(1,123,32,4,312,4)
tu.count(4)

2

In [56]:
tu=(1,123,32,4,312,4)
tu.index(32)

2

In [59]:
se={1,22,33,3,1}
se.add(41)
se

{1, 3, 22, 33, 41}

In [58]:
se={1,22,33,3,1,}
se.clear()
se

set()

In [26]:
se={1,22,33,3,1,}
se.copy()

{1, 3, 22, 33}

In [27]:
setA = {1,2,3,4,5}
setB = {10,3,4,5,6}
setA.difference(setB)

{1, 2}

In [63]:
setA = {1,2,3,4,5}
setB = {10,3,4,5,6}
setA.difference_update(setB)
setA

{1, 2}

In [29]:
se={1,22,33,3,1,}
se.discard(123)
se

{1, 3, 22, 33}

In [30]:
setA = {1,2,3,4,5}
setB = {10,3,4,5,6}
setA.intersection(setB)
setA

{1, 2, 3, 4, 5}

In [31]:
setA = {1,2,3,4,5}
setA.intersection_update({4,5,55,3,2,22})
setA


{2, 3, 4, 5}

In [70]:
setA = {1,2,3,4,5}
setA.intersection_update({4,5,55,3,2,22})
setA


{2, 3, 4, 5}

In [67]:
se={1,22,33,3,1,}
s={22,3,1}
s.issubset(se)


True

In [69]:

se.issuperset(s)


True

In [70]:

print(se.pop())
print(se)


1
{3, 22, 33}


In [35]:
se={1,22,33,3,1,}
print(se)
se.remove(3)
se

{1, 3, 22, 33}


{1, 22, 33}

In [36]:
setA = {1,2,3,4,5}
setB = {10,3,4,5,6}
setA.symmetric_difference(setB)

{1, 2, 6, 10}

In [37]:
setA = {1,2,3,4,5}
setB = {10,3,4,5,6}
setA.symmetric_difference_update(setB)
setA

{1, 2, 6, 10}

In [38]:
setA = {1,2,3,4,5}
setB = {10,3,4,5,6}
setA.union(setB)


{1, 2, 3, 4, 5, 6, 10}

In [71]:

setA.update(setB)
setA

{1, 2, 3, 4, 5, 6, 10}